nome = input('Qual é o seu nome?')
print('Olá',nome,'é um prazer!')
idade = input('Qual é a sua idade?')
peso = input('Qual é o seu peso?')
print(nome, idade, peso)
print('Seja bem-vindo de volta',nome,'!')