nome = str(input('Digite seu nome completo:')).strip()
print('Analizando seu nome...')
print(nome.upper())
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
esp = (nome.count(' '))
print('Seu nome tem ao todo {} letras'.format(len(nome) - esp))
letras = (nome.find(' '))
#print('Seu primeiro nome tem {} letras'.format(letras))
s = nome.split()
print('Seu primeiro nome é {} e ao todo ele possui {} letras.'.format(s[0],len(s[0])))
